# Generated by Django 3.2.4 on 2021-10-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Currency', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=200)),
                ('gas_emitted', models.IntegerField()),
                ('co2_emitted', models.IntegerField()),
            ],
        ),
    ]
